### ISSUE TITLE
Extra img file in root

### ISSUE THREAD

**Issue by ekubokirs** [ga-students/FEWD-DC-25#1]
There's a hanging img file that looks like its supposed to be in Week 5 Lesson 10

**Comment by jserrao** [comment]
In which week are you seeing this issue?

**Comment by ekubokirs** [comment]
It was in the general root repo at the bottom

**Comment by jserrao** [comment]
Got it, thanks.

**Comment by jserrao** [comment]
https://github.com/ga-students/FEWD-DC-25/commit/5d492dc89cc283da87580c9bcfa1dfa5c96f654a
